from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys

browser=webdriver.Firefox()
browser.get('https://gmail.com')

ac=browser.find_element_by_id('identifierId')
ac.clear()
ac.send_keys('username'+Keys.ENTER)
time.sleep(5)
ps=browser.find_element_by_name('password')
ps.send_keys('password'+Keys.ENTER)
time.sleep(10)
com=browser.find_element_by_xpath("//div[@gh='cm']")
com.click()
time.sleep(5)
pop=browser.find_element_by_xpath('//img[@alt="Pop-out"]')
pop.click()
to=browser.find_element_by_xpath('//textarea[@name="to"]')
to.send_keys('receiver@mail.address'+Keys.ENTER)
fro=browser.find_element_by_id(":k3")
va=browser.find_element_by_xpath("//div[@value='selected@another.address']")
fro.click()
va.click()
subject=browser.find_element_by_xpath('//input[@name="subjectbox"]')
subject.send_keys('Title')
time.sleep(5)
content=browser.find_element_by_xpath('//div[@aria-label="Message Body"]')
content.click()
content.send_keys('Content')
content.send_keys(Keys.LEFT_CONTROL+Keys.ENTER)
